spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

security:
  lifetime: 60000

server:
  port: 8080